// Generated by https://quicktype.io

export interface Characters {
  filter(arg0: (data: any) => boolean): any;
  info: Info;
  results: Result[];
}

export interface Info {
  count: number;
  pages: number;
  next: string;
  prev: null;
}

export interface Result {
  id: number;
  name: string;
  status: Status;
  species: Species;
  type: string;
  gender: Gender;
  origin: LocationIn;
  location: LocationIn;
  image: string;
  episode: string[];
  url: string;
  created: string;
}

export enum Gender {
  Female = 'Female',
  Male = 'Male',
  Unknown = 'unknown',
}

export interface LocationIn {
  name: string;
  url: string;
}

export interface Location {
  filter(arg0: (data: any) => boolean): any;
  info: Info;
  results: ResultLocation[];
}

export interface ResultLocation {
  id: number;
  name: string;
  type: string;
  dimension: string;
  residents: Characters[];
  url: string;
  created: string;
}

export enum Species {
  Alien = 'Alien',
  Human = 'Human',
}

export enum Status {
  Alive = 'Alive',
  Dead = 'Dead',
  Unknown = 'unknown',
}
